version: '3'
services:
  app:
    container_name: StickerSmash
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - './:/app'
      - '/app/node_modules'
